[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = [
  "npm install",
  "npm --prefix backend install",
  "npm --prefix frontend install",
  "npm --prefix admin install"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build",
  "npm --prefix admin run build"
]

[start]
cmd = "node backend/server.js"
